name: Deploy to DigitalOcean

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-recipes:latest

            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.DROPLET_SSH_KEY }}
                  known_hosts: unnecessary

            - name: Adding Known Hosts
              run: ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

            - name: Deploy to DigitalOcean droplet
              run: |
                ssh ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} << 'ENDSSH'
                  # Update packages
                  sudo apt-get update
                
                  # Install Docker if not already installed
                  if ! command -v docker &> /dev/null; then
                    sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
                    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
                    sudo apt-get update
                    sudo apt-get install -y docker-ce
                  fi
                
                  # Pull the latest image
                  docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ai-recipes:latest
                
                  # Stop and remove the old container
                  docker stop ai-recipes-web || true
                  docker rm ai-recipes-web || true
                
                  # Run the new container
                  docker run -d --name ai-recipes-web \
                    -p 80:3000 \
                    -e OPENAI_API_KEY="${OPENAI_API_KEY}" \
                    ${{ secrets.DOCKERHUB_USERNAME }}/ai-recipes:latest
                
                  # Clean up unused Docker resources
                  docker system prune -af
                ENDSSH